[package]
name = "githubsearchtool"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = {version= "0.12.5" ,  features = ["json"]}
serde = {version="1.0.204" , features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38.1", features = ["full"] }



